<?php
/**
 * Bundled calendar data (data/*.php, generated by scripts/build-plugin.mjs).
 * Each file returns a PHP array, cached by OPcache, so lookups cost no parsing or queries.
 */

defined( 'ABSPATH' ) || exit;

/** Loads a bundled data file once per request. */
function wdtprs_ordo_data( $name ) {
	static $cache = array();
	if ( ! array_key_exists( $name, $cache ) ) {
		$file           = WDTPRS_ORDO_DIR . 'data/' . $name . '.php';
		$cache[ $name ] = is_readable( $file ) ? include $file : array();
	}
	return $cache[ $name ];
}

/** Both calendars for one date (Y-m-d): [ 'no' => [...], 'vo' => [...] ], or null outside the bundled years. */
function wdtprs_ordo_day( $date ) {
	if ( ! preg_match( '/^(\d{4})-\d{2}-\d{2}$/', $date, $m ) ) {
		return null;
	}
	$year = wdtprs_ordo_data( 'days-' . $m[1] );
	return $year[ $date ] ?? null;
}

/** First and last bundled dates. */
function wdtprs_ordo_range() {
	static $range;
	if ( null === $range ) {
		$years = array();
		foreach ( glob( WDTPRS_ORDO_DIR . 'data/days-*.php' ) as $f ) {
			$years[] = (int) substr( basename( $f, '.php' ), 5 );
		}
		sort( $years );
		$range = $years ? array( $years[0] . '-01-01', end( $years ) . '-12-31' ) : array( '', '' );
	}
	return $range;
}

/** Name and calendar of a key; [ 'f' => 'no'|'vo', 'n' => name, 'd' => dates ]. */
function wdtprs_ordo_key( $key ) {
	$keys = wdtprs_ordo_data( 'keys' );
	return $keys[ $key ] ?? null;
}

/** Next date (on or after $from) a key is celebrated, or the last one if it has passed. */
function wdtprs_ordo_next_date( $key, $from ) {
	$info = wdtprs_ordo_key( $key );
	if ( ! $info || empty( $info['d'] ) ) {
		return null;
	}
	foreach ( $info['d'] as $d ) {
		if ( $d >= $from ) {
			return $d;
		}
	}
	return end( $info['d'] );
}

/** Today in the site's time zone (readers' local dates are handled in JavaScript). */
function wdtprs_ordo_today() {
	return wp_date( 'Y-m-d' );
}

function wdtprs_ordo_color_name( $c ) {
	$names = array(
		'WHITE'  => __( 'White', 'wdtprs-ordo' ),
		'RED'    => __( 'Red', 'wdtprs-ordo' ),
		'GREEN'  => __( 'Green', 'wdtprs-ordo' ),
		'PURPLE' => __( 'Violet', 'wdtprs-ordo' ),
		'ROSE'   => __( 'Rose', 'wdtprs-ordo' ),
		'BLACK'  => __( 'Black', 'wdtprs-ordo' ),
		'GOLD'   => __( 'Gold', 'wdtprs-ordo' ),
	);
	return $names[ $c ] ?? '';
}

/** Short form labels. */
function wdtprs_ordo_forms() {
	return array(
		'vo' => array( 'label' => __( 'Vetus Ordo', 'wdtprs-ordo' ), 'sub' => __( '1962 Missal · 2020 USA calendar', 'wdtprs-ordo' ), 'short' => '1962' ),
		'no' => array( 'label' => __( 'Novus Ordo', 'wdtprs-ordo' ), 'sub' => __( '2002 Missal', 'wdtprs-ordo' ), 'short' => 'NO' ),
	);
}
