// Packages the WordPress plugin: writes wp-plugin/wdtprs-ordo/data/*.php from src/data/*.json
// (run `npm run data` first) and zips the plugin into dist-plugin/wdtprs-ordo-<version>.zip
// for Plugins → Add New → Upload.
//
// Data is emitted as PHP array literals (not JSON) so OPcache keeps it in shared memory:
// looking up a day costs no parsing and no database query.
import { readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';

const PLUGIN = 'wp-plugin/wdtprs-ordo';
const days = JSON.parse(await readFile('src/data/days.json', 'utf8'));
const posts = JSON.parse(await readFile('src/data/posts.json', 'utf8'));
const index = JSON.parse(await readFile('src/data/index.json', 'utf8'));

// --- PHP literal writer ---
const q = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
function php(v) {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'string') return q(v);
  if (Array.isArray(v)) return `[${v.map(php).join(',')}]`;
  return `[${Object.entries(v).filter(([, x]) => x !== undefined && x !== null && !(Array.isArray(x) && !x.length))
    .map(([k, x]) => `${/^\d+$/.test(k) ? k : q(k)}=>${php(x)}`).join(',')}]`;
}
const file = (comment, value) => `<?php\n// ${comment}\n// Generated by scripts/build-plugin.mjs — do not edit.\nreturn ${php(value)};\n`;

// --- days, one file per year ---
const compactNo = (d) => d && {
  n: d.name, r: d.rank, c: d.color, s: d.season, y: d.cycle, k: d.keys, w: d.weekKey, wn: d.weekName,
  x: d.celebrations?.slice(1).map((c) => c.name),
};
const compactVo = (d) => d && {
  n: d.name, r: d.rank, c: d.color, cn: d.colorNote, l: d.link, k: d.keys, w: d.weekKey, wn: d.weekName,
  a: d.alt?.map((a) => [a.key, a.name, a.label === 'Commemorated' ? 'c' : 's']),
};
const byYear = {};
for (const [date, d] of Object.entries(days)) {
  (byYear[date.slice(0, 4)] ||= {})[date] = { no: compactNo(d.no), vo: compactVo(d.vo) };
}
await rm(`${PLUGIN}/data`, { recursive: true, force: true });
await mkdir(`${PLUGIN}/data`, { recursive: true });
for (const [year, list] of Object.entries(byYear)) {
  await writeFile(`${PLUGIN}/data/days-${year}.php`, file(`Liturgical days for ${year}: date => [no, vo]`, list));
}

// --- keys: display name, calendar, and every date it falls on (for "next on …") ---
const keys = {};
const note = (key, form, name, date) => {
  if (!key) return;
  keys[key] ||= { f: form, n: name, d: [] };
  if (date && keys[key].d.at(-1) !== date) keys[key].d.push(date);
};
for (const [date, d] of Object.entries(days).sort(([a], [b]) => a.localeCompare(b))) {
  if (d.no) d.no.celebrations.forEach((c, i) => note(d.no.keys[i], 'no', c.name, date));
  if (d.no?.extra) note(d.no.extra.key, 'no', d.no.extra.name, date);
  if (d.vo) note(d.vo.keys[0], 'vo', d.vo.name, date);
  for (const a of d.vo?.alt || []) note(a.key, 'vo', a.name, null);
}
// Matched keys keep the matcher's display name even if no day in range uses it.
for (const p of posts) for (const [form, m] of Object.entries(p.matches)) note(m.key, form, m.name, null);
await writeFile(`${PLUGIN}/data/keys.php`, file('Liturgical day key => [f: calendar, n: name, d: dates]', keys));

// --- posts: prayer text and grouping for matched and same-prayer posts; tag assignments ---
const assignments = {};
const postInfo = {};
for (const p of posts) {
  const ks = Object.values(p.matches).map((m) => m.key);
  if (ks.length) assignments[p.id] = ks;
  if (ks.length || (p.incipit && index.byIncipit[p.incipit])) {
    postInfo[p.id] = { p: p.part, la: p.latin, li: p.literal, i: p.incipit };
  }
}
await writeFile(`${PLUGIN}/data/assignments.php`, file('Post ID => liturgical day keys, from the title matcher (imported once)', assignments));
await writeFile(`${PLUGIN}/data/posts.php`, file('Post ID => [p: prayer part, la: Latin, li: literal rendering, i: incipit]', postInfo));
await writeFile(`${PLUGIN}/data/incipits.php`, file('Incipit => post IDs discussing the same Latin prayer', index.byIncipit));

// --- zip ---
const version = (await readFile(`${PLUGIN}/wdtprs-ordo.php`, 'utf8')).match(/Version:\s*([\d.]+)/)[1];
await mkdir('dist-plugin', { recursive: true });
const zip = `dist-plugin/wdtprs-ordo-${version}.zip`;
await rm(zip, { force: true });
execFileSync('zip', ['-qr', `../${zip}`, 'wdtprs-ordo', '-x', '*.DS_Store'], { cwd: 'wp-plugin' });
console.log(`years ${Object.keys(byYear).join(', ')} | ${Object.keys(keys).length} keys | ${Object.keys(assignments).length} posts to tag -> ${zip}`);
